server:
  port: 8080

spring:
  application:
    name: demo1

  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cjqusmaosj3q.ap-northeast-2.rds.amazonaws.com/economy?autoReconnect=true
    username: admin
    password: jenny0930*

jwt:
  expiration_time: 86400000
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa