server:
  port: 9000

spring:
  application:
    name: demo1

  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/economy?autoReconnect=true
    username: root
    password: 0930

jwt:
  expiration_time: 86400000
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa